### ISSUE TITLE
laser inverted

### ISSUE THREAD

**Issue by malsbier** [iandouglas96/engravR#4]
Hey,
Got someone the same problem?
I am running on a raspberry pi 1 with raspbian jessie lite 4.4, python 2.7.9 with numpy and pexpect.
I have generated my gcode with inkscape 0.48 and gcodetools, like in the video.
My laser turns on, when it should be turned off and on when not.
For example in the fast movement the laser is on and wihle engraving mode the laser is off.
I have tried different gpio for the laser, everytime the same problem.
Pls help

**Comment by malsbier** [comment]
I can fix the problem by changing the laseron() command to GPIO.output(Laser_switch,False); and the other way round, in every linewhere it is used, in the laserengraver file.
But thats not a real solution of my problem, please help.

**Comment by iandouglas96** [comment]
You did exactly what I would suggest (changing the polarity of the Laser GPIO).  What I suspect is happening is that your laser driver circuitry is slightly different from mine.  There are 2 kinds of FET transistors: nFETs and pFETs.  Both act as switches, but for an nFET, "1" is on, and "0" is off.  However, for a pFET, "0" is on and "1" is off.  I used an nFET in my circuit, you probably used a pFET.  It doesn't really matter either way, you will just have to do the exact code modification you have already done.
